In [1]:
import pandas as pd

In [2]:
path = "../pitch/GPS_cmd_16k_renamed_pyin_avg_by_word_user.csv"
df = pd.read_csv(path)
df

,filepaths,users,genders,words,f0
0,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F001,F,academia,207
1,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F001,F,academia,207
2,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F001,F,academia,207
3,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F001,F,academia,207
4,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F001,F,academia,207
...,...,...,...,...,...
3995,/home/jovyan/work/OneDrive/Documentos/Doutorad...,M020,M,trabalho,102
3996,/home/jovyan/work/OneDrive/Documentos/Doutorad...,M020,M,trabalho,102
3997,/home/jovyan/work/OneDrive/Documentos/Doutorad...,M020,M,trabalho,102
3998,/home/jovyan/work/OneDrive/Documentos/Doutorad...,M020,M,trabalho,102
3999,/home/jovyan/work/OneDrive/Documentos/Doutorad...,M020,M,trabalho,102

### Setup 1

file: ../pitch/GPS_cmd_16k_renamed_pyin_avg_by_word_user.csv

users F/M = 20 -  train: 14, val: 2, test: 4

Test: F017 F018 F019 F020 M017 M018 M019 M020

Val: F015 F016 M015 M016

Train: restante

In [3]:
df_test = df[(df["users"] == "F017") | (df["users"] == "F018") | (df["users"] == "F019") | (df["users"] == "F020") \
| (df["users"] == "M017") | (df["users"] == "M018") | (df["users"] == "M019") | (df["users"] == "M020")].reset_index(drop=True)

In [4]:
df_val = df[(df["users"] == "F015") | (df["users"] == "F016") | (df["users"] == "M015") | (df["users"] == "M016")].reset_index(drop=True)

In [5]:
df_diff = df.merge(df_test, how='outer', indicator=True).loc[lambda x : x['_merge'] == 'left_only'].drop(columns=['_merge'])

In [6]:
df_train = df_diff.merge(df_val, how='outer', indicator=True).loc[lambda x : x['_merge'] == 'left_only'].drop(columns=['_merge'])

In [7]:
"Train: ", len(df_train), "Val: ", len(df_val), "Test: ", len(df_test)

('Train: ', 2800, 'Val: ', 400, 'Test: ', 800)

In [8]:
abs_path = "../lists/GPS_cmd_pyin_setup_1"
df_train.to_csv(f"{abs_path}_train.csv", index=False)
df_val.to_csv(f"{abs_path}_val.csv", index=False)
df_test.to_csv(f"{abs_path}_test.csv", index=False)

In [9]:
df_test

,filepaths,users,genders,words,f0
0,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F017,F,academia,258
1,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F017,F,academia,258
2,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F017,F,academia,258
3,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F017,F,academia,258
4,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F017,F,academia,258
...,...,...,...,...,...
795,/home/jovyan/work/OneDrive/Documentos/Doutorad...,M020,M,trabalho,102
796,/home/jovyan/work/OneDrive/Documentos/Doutorad...,M020,M,trabalho,102
797,/home/jovyan/work/OneDrive/Documentos/Doutorad...,M020,M,trabalho,102
798,/home/jovyan/work/OneDrive/Documentos/Doutorad...,M020,M,trabalho,102
799,/home/jovyan/work/OneDrive/Documentos/Doutorad...,M020,M,trabalho,102

In [13]:
df_test_F = df_test[df_test["genders"] == "F"]
df_test_F

,filepaths,users,genders,words,f0
0,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F017,F,academia,258
1,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F017,F,academia,258
2,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F017,F,academia,258
3,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F017,F,academia,258
4,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F017,F,academia,258
...,...,...,...,...,...
755,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F020,F,trabalho,113
756,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F020,F,trabalho,113
757,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F020,F,trabalho,113
758,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F020,F,trabalho,113
759,/home/jovyan/work/OneDrive/Documentos/Doutorad...,F020,F,trabalho,113

### Setup 2